version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres-emprestimo
    environment:
      POSTGRES_DB: emprestimo-livros  # Nome do banco de dados
      POSTGRES_USER: postgres         # Nome do usuário
      POSTGRES_PASSWORD: 1996         # Senha do usuário
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - emprestimo-network

volumes:
  postgres_data:

networks:
  emprestimo-network:
    driver: bridge
